# Assignment #4: NumPy + Tuple, Set, Dict




### In this assignment, we will practice on NumPy, Tuple, Set, Dict using social network use case.

**Please read the explanation in [here](https://drive.google.com/file/d/13h-wDYixvxn2er8zO13z4_hNgcT6S7nt/view?usp=share_link).**

# **Important**
- Do not delete or modify the first line in the given code cell.
- You work must be add in the provided area only.
- You must not change the declaration of the provided functions.
- You are allowed to add your own functions.
- If you want to write your own program to test, add new code cell at the very end of the file and add your code there.


In [ ]:
import numpy as np

In [1]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Function 1

def generate_followed_by_dict(infile):
    # write your code here
    followed_by = {}
    f = open(infile, "r")
    s = f.readlines()
    for i in range(len(s)):
        s[i] = s[i].strip('\n').split(',')
        followed_by[s[i][0]] = s[i][1:]


    return followed_by

In [2]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Function 2

def generate_followed_by_matrix(followed_by_dict):
    # write your code here
    person_names = list(followed_by_dict.keys())
    for i in followed_by_dict:
        for j in followed_by_dict[i]:
            if j not in person_names:
                # print(j)
                person_names.append(j)
    person_names = sorted(person_names)

    for name in person_names:
        if name not in followed_by_dict:
            followed_by_dict[name] = []

    followed_by_dict2 = {}
    for k, v in sorted(followed_by_dict.items()):
        followed_by_dict2[k] = v

    n = len(person_names)

    matrix = np.zeros((n, n), dtype = int)
    for k, v in followed_by_dict.items():
        for i in v:
            matrix[person_names.index(k)][person_names.index(i)] = 1
            #print(str(k),end='')
            #print(person_names.index(i))

    return matrix, person_names


In [3]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Function 3

def generate_degree_matrix(A):
    # write your code here
    total = np.sum(A, axis=1)
    #print(total)
    degree_matrix = np.zeros_like(A)
    for i in range(A.shape[0]):
        degree_matrix[i][i] = total[i]

    return degree_matrix



In [4]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Function 4

def get_top_influencer(M, person_names):
    # write your code here
    degree_matrix = generate_degree_matrix(M)
    top = np.max(degree_matrix)
    #print(top)
    top_list = []
    for i in range(degree_matrix.shape[0]):
        if degree_matrix[i][i] == top:
            top_list.append(person_names[i])

    return top_list



In [5]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Function 5

def generate_similarity_matrix_among_influencers(M, person_names):
    # write your code here
    n = M.shape[0]
    #print(n)
    for i in reversed(range(n)):
        isZero = M[i]==0
        if all([x for x in isZero == True]):
            M = np.delete(M, (i), axis=0)
            person_names.pop(i)
    #print(person_names)
    #print(M)
    N = np.zeros_like(M, float)

    n = M.shape[0]
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            #print(person_names[i], person_names[j])
            a = np.sum(M[i])
            b = np.sum(M[j])
            #print(a, b)
            C = (M[i] + M[j])
            C = C[C == 2]
            c = len(C)
            #print(c)
            N[i][j] = round(c/(a+b-c), 2)
            #print(M[i][j])
            #print('----')

    N = N[:, :N.shape[0]]
    return N, person_names


In [6]:
# DO NOTE DELETE THIS CELL / WRITE YOUR CODE HERE
# Function 6

def  get_all_pairs_of_most_similar_influencers(S, only_influencers):
    # write your code here
    n = S.shape[0]
    max = np.max(S)
    pairs = []
    for i in range(n):
        for j in range(i+1, n):
            if S[i, j] == max:
                pairs.append((only_influencers[i], only_influencers[j]))

    return pairs


### --- Testcase 1 --- ###
#### You can get infile_1.txt from [here](https://drive.google.com/file/d/1-JO6bfUHy4G_Y1ouAYmap5SgBgZgds87/view?usp=share_link) ####

In [ ]:
# Testcase 1
# link to get infile_1.txt
followed_by_dict = generate_followed_by_dict("infile_1.txt")
print(followed_by_dict)
M, person_names = generate_followed_by_matrix(followed_by_dict)
print("M = ", M)
print("person_names", person_names)
D = generate_degree_matrix(M)
print("D = ", D)
print("top influencers = ", get_top_influencer(M, person_names))
S, all_influencers = generate_similarity_matrix_among_influencers(M, person_names)
print("similarity_matrix = ", S)
print(all_influencers)

pairs = get_all_pairs_of_most_similar_influencers(S, all_influencers)
print(pairs)

#### Expected output of Testcase 1 ####

{'A': ['E'], 'B': ['A', 'D'], 'C': ['E', 'B'], 'D': ['A', 'E']}
M =  [[0 0 0 0 1]
 [1 0 0 1 0]
 [0 1 0 0 1]
 [1 0 0 0 1]
 [0 0 0 0 0]]
person_names ['A', 'B', 'C', 'D', 'E']
D =  [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 2 0 0]
 [0 0 0 2 0]
 [0 0 0 0 0]]
top influencers =  ['B', 'C', 'D']
similarity_matrix =  [[0.   0.   0.5  0.5 ]
 [0.   0.   0.   0.33]
 [0.5  0.   0.   0.33]
 [0.5  0.33 0.33 0.  ]]
['A' 'B' 'C' 'D']
[('A', 'C'), ('A', 'D')]

### --- Testcase 2 --- ###
#### You can get infile_2.txt from [here](https://drive.google.com/file/d/1CPhOVlGJTbGTjmXYBSZ7ksnrAbt7YGyP/view?usp=share_link) ####

In [7]:
# Testcase 2
followed_by_dict = generate_followed_by_dict("infile_2.txt")
print(followed_by_dict)
M, person_names = generate_followed_by_matrix(followed_by_dict)
print("M = ", M)
print("person_names", person_names)
D = generate_degree_matrix(M)
print("D = ", D)
print("top influencers = ", get_top_influencer(M, person_names))
SM, all_influencers = generate_similarity_matrix_among_influencers(M, person_names)
print("similarity_matrix = ", SM)
print(all_influencers)

pairs = get_all_pairs_of_most_similar_influencers(SM, all_influencers)
print(pairs)

FileNotFoundError: ignored

#### Expected output of Testcase 2 ####

{'A': ['B', 'C', 'D', 'E'], 'Q': ['F', 'H', 'I']}
M =  [[0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0]]
person_names ['A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'Q']
D =  [[4 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 3]]
top influencers =  ['A']
similarity_matrix =  [[0. 0.]
 [0. 0.]]
['A' 'Q']
[]

### --- Testcase 3 --- ###
#### You can get infile_3.txt from [here](https://drive.google.com/file/d/1Xwe48zFV43s7nAkmtEqVWdXoAlTswLkI/view?usp=share_link) ####

In [ ]:
# Testcase 3
followed_by_dict = generate_followed_by_dict("infile_3.txt")
print(followed_by_dict)
M, person_names = generate_followed_by_matrix(followed_by_dict)
print("M = ", M)
print("person_names", person_names)
D = generate_degree_matrix(M)
print("D = ", D)
print("top influencers = ", get_top_influencer(M, person_names))
SM, all_influencers = generate_similarity_matrix_among_influencers(M, person_names)
print("similarity_matrix = ", SM)
print(all_influencers)

pairs = get_all_pairs_of_most_similar_influencers(SM, all_influencers)
print(pairs)

#### Expected output of Testcase 3 ####

{'A': ['B', 'C', 'D', 'E', 'Q'], 'Q': ['F', 'H', 'I', 'A'], 'R': ['B', 'C', 'D', 'E', 'A']}
M =  [[0 1 1 1 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 1 1 0 0]
 [1 1 1 1 1 0 0 0 0 0]]
person_names ['A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'Q', 'R']
D =  [[5 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 5]]
top influencers =  ['A', 'R']
similarity_matrix =  [[0.   0.   0.67]
 [0.   0.   0.12]
 [0.67 0.12 0.  ]]
['A' 'Q' 'R']
[('A', 'R')]

### --- Testcase 4 --- ###
#### You can get infile_4.txt from [here](https://drive.google.com/file/d/1OZZO5Muq0iviRSPwEWIfvWm_G3c4ktf4/view?usp=share_link) ####

In [ ]:
# Testcase 4
followed_by_dict = generate_followed_by_dict("infile_4.txt")
print(followed_by_dict)
M, person_names = generate_followed_by_matrix(followed_by_dict)
print("M = ", M)
print("person_names", person_names)
D = generate_degree_matrix(M)
print("D = ", D)
print("top influencers = ", get_top_influencer(M, person_names))
SM, all_influencers = generate_similarity_matrix_among_influencers(M, person_names)
print("similarity_matrix = ", SM)
print(all_influencers)

pairs = get_all_pairs_of_most_similar_influencers(SM, all_influencers)
print(pairs)

#### Expected output of Testcase 4 ####

{'A': ['B', 'C', 'D', 'E', 'Q', 'P'], 'B': ['A', 'C', 'D', 'E'], 'C': ['D', 'E'], 'D': ['A', 'B', 'C', 'E'], 'E': ['A', 'B', 'C', 'D']}
M =  [[0 1 1 1 1 1 1]
 [1 0 1 1 1 0 0]
 [0 0 0 1 1 0 0]
 [1 1 1 0 1 0 0]
 [1 1 1 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
person_names ['A', 'B', 'C', 'D', 'E', 'P', 'Q']
D =  [[6 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
top influencers =  ['A']
similarity_matrix =  [[0.   0.43 0.33 0.43 0.43]
 [0.43 0.   0.5  0.6  0.6 ]
 [0.33 0.5  0.   0.2  0.2 ]
 [0.43 0.6  0.2  0.   0.6 ]
 [0.43 0.6  0.2  0.6  0.  ]]
['A' 'B' 'C' 'D' 'E']
[('B', 'D'), ('B', 'E'), ('D', 'E')]

### --- Testcase 5 --- ###
#### You can get infile_5.txt from [here](https://drive.google.com/file/d/1DsHlLf3s5YEem4jNeQM_XMbefce67kfA/view?usp=share_link) ####

In [ ]:
# Testcase 5
followed_by_dict = generate_followed_by_dict("infile_5.txt")
print(followed_by_dict)
M, person_names = generate_followed_by_matrix(followed_by_dict)
print("M = ", M)
print("person_names", person_names)
D = generate_degree_matrix(M)
print("D = ", D)
print("top influencers = ", get_top_influencer(M, person_names))
SM, all_influencers = generate_similarity_matrix_among_influencers(M, person_names)
print("similarity_matrix = ", SM)
print(all_influencers)

pairs = get_all_pairs_of_most_similar_influencers(SM, all_influencers)
print(pairs)

#### Expected output of Testcase 5 ####

{'A': ['Q'], 'Q': ['A']}
M =  [[0 1]
 [1 0]]
person_names ['A', 'Q']
D =  [[1 0]
 [0 1]]
top influencers =  ['A', 'Q']
similarity_matrix =  [[0. 0.]
 [0. 0.]]
['A' 'Q']
[]